language: r
cache: packages
sudo: required

matrix:
  include:
    - dist: focal
    - os: osx
      brew_packages: llvm

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then rm "/usr/local/bin/gfortran"; fi

addons:
  apt:
    sources:
      - sourceline: "ppa:ubuntugis/ubuntugis-unstable"
    packages:
      - libudunits2-dev
      - libproj-dev
      - libgeos-dev
      - libgdal-dev

r_packages:
  - covr

after_success:
  - Rscript -e 'library(covr); codecov()'
